CREATE DATABASE customer_analytics;
SELECT*FROM customer LIMIT 20;
--Q-1 What is the total revenue generated by male vs female customers?
SELECT gender, SUM(purchase_amount) as revenue
FROM customer
group by gender;

--Q-2 Which customer used a discount but still spent more than the average puchase amount?
SELECT customer_id,purchase_amount
FROM customer
WHERE discount_applied="Yes" and purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);

--Q-3 Which are the top 5 products with the highest average rating?
SELECT item_purchased, ROUND(AVG(review_rating),2) as "Average Product Rating"
FROM customer
group by item_purchased
order by avg(review_rating) desc
LIMIT 5;

--Q-4 Compare the average purchase amount between standerd and express shipping?
SELECT shipping_type,
ROUND(AVG(purchase_amount),2)
FROM customer
WHERE shipping_type in ("Standard","Express")
group by shipping_type

--Q-5 Do subscribed customers spend more? Comapre average spend and total revenue between subscribers and non-subscribers.
 SELECT subscription_status,
 COUNT(customer_id) as total_customers,
 ROUND(AVG(purchase_amount),2) as avg_spend,
 ROUND(SUM(purchase_amount),2)as total_revenue
 FROM customer
 group by subscription_status
 order by total_revenue, avg_spend desc;
 
 --Q-6 Which 5 products have the highest percentage of purchases with discounts applied?
 SELECT item_purchased,
 ROUND(100 * SUM(CASE WHEN discount_applied = "yes" THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
 FROM customer
 group by item_purchased
 order by discount_rate desc
 LIMIT 5;
 
 --Q-7 Suggest customer into New, Returning , and Loyal based on their total number of previous purchase, and slow the count of each segment.
 with customer_type as (
 SELECT customer_id, previous_purchases,
 CASE
     WHEN previous_purchases =1 THEN "New"
     WHEN previous_purchases BETWEEN 2 AND 10 THEN "Returning"
     ELSE "Loyal"
     END AS customer_segment
FROM customer
)
SELECT customer_segment, count(*) as "Number of customers"
from customer_type
group by customer_segment

 --Q-8 What are the top 3 most purchsed products within each category?
 with item_counts as (
 SELECT category,
 item_purchased,
 COUNT(customer_id) as total_orders,
 ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
 FROM customer
 group by category, item_purchased
 )
 SELECT item_rank, category, item_purchased, total_orders
 from item_counts
 where item_rank <= 3;
 --Q-9 Are customers who are repeat buyers (more than 5 previous purchase) also likely to subscribe
 SELECT subscription_status,
 count(customer_id) as repeat_buyers
 FROM customer
 WHERE previous_purchases > 5
 group by subscription_status
 
 --Q-10 What is the revenue contribution of each age group?
 SELECT age_group,
 SUM(purchase_amount) as total_revenue
 from customer
 group by age_group
 order by total_revenue desc;